[workspace]
name = "soma-env-0.0"
channels = ["conda-forge", "pytorch", "nvidia", "https://brainvisa.info/neuro-forge"]
platforms = ["linux-64"]
version = "0.0"

[dependencies]
python = "=3.12" # Most recent release compatible with all dependencies

#gcc = "<15" # Install clang instead of gcc during compilation compatibility process.
#gxx = "<15" #  We will have to choose one.

clang = "*"
lld = "*"
libcxx = "*"

# The following packages are not (yet ?) compatibl with Qt6.
# qtconsole = "*" # depends on pyqt 5
# pyqtwebengine = "*" # depends on pyqt 5

pytorch = { version="*", channel="pytorch" }
torchvision = { version="*", channel="pytorch" }
typer = "*"
conda-build = "*"
pyyaml = "*"
dateutils = "*"
cmake = "*"
git = "*"
git-lfs="*"
gitpython = "*"
libglu = "*"
libglvnd-devel-cos7-x86_64 = "*"
libstdcxx-devel_linux-64 = "*"
make = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesalib-devel-only = "*"
pip = "*"
pyaml = "*"
pytest = "*"
rattler-build = ">=0.13"
six = "*"
sphinx = "*"
toml = "*"
virtualgl = "*"
"sigcpp-2.0" = "*"
libblitz = "*"
libboost-devel = "*"
gfortran = "*"
numpy = "*"
libminc = "*"
openjpeg = "*"
pywebp = "*"
objgraph = "*"
graphviz = "*"
doxygen = "*"
pkgconfig = "*"
nipype = "*"
xlrd = "*"
xlwt = "*"
openpyxl = "*"
lark-parser = ">0.7.0"
python-dateutil = "*"
requests = "*"
cryptography = "*"
scikit-learn = "*"
configobj = "*"
# pyqtwebkit = "*"
scipy = "*"
traits = { version = "*", build = "*" }
spm12 = "*"
reportlab = "*"
libsvm = "*"
pcl = "*"
qwt = "*"
qt6-multimedia = "*"
qt6-webengine = "*"
dcmtk = ">=3.7"
matplotlib = "*"
ipycanvas = "*"
ipywidgets = "*"
ipyevents = "*"
notebook = "*"
pygltflib = "*"
nodejs = "*"
xvfb = "*"
mesalib_software = "*"
pyqt6 = "*"
ipykernel = "*"
pycryptodome = "*"
pandas = "*"
libgl = "*"
libopengl = "*"
pydicom = "*"
pre-commit = "*"
scikit-image = "*"
gdb = "*"
sphinxcontrib-mermaid = "*"
myst-parser = "*"
sphinx-rtd-theme = "*"
sphinx-gallery = "*"
nbsphinx = "*"
nbconvert-pandoc = "*"
soma-openslide = "*"
black = "*"
dracopy = "*"
python-build = "*"
twine = "*"
gltf-transform = "*"
pyzmq = "*"
paramiko = "*"
wkhtmltopdf = "*"
filelock = "*"
libxml2-devel = "*"

[dependencies.libjpeg-turbo]
channel = "conda-forge"
version = ">=3.0.0"

[activation]
scripts = ["activate.sh"]
